# Generated by Django 3.1.7 on 2021-02-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('BirthDate', models.DateTimeField()),
                ('City', models.CharField(max_length=255)),
                ('Egn', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Accomodation', models.BooleanField(default=False)),
                ('LicensePlate', models.CharField(max_length=255)),
                ('PhoneNumber', models.CharField(max_length=255)),
            ],
        ),
    ]
