# Generated by Django 3.1.7 on 2021-02-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Accomodation',
            new_name='accomodation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='BirthDate',
            new_name='birthDate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Egn',
            new_name='egn',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='FirstName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='LastName',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='LicensePlate',
            new_name='licensePlate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='PhoneNumber',
            new_name='phoneNumber',
        ),
    ]
